### ISSUE TITLE
Cleanup: remove old step files, scripts, rearrange steps

### ISSUE THREAD

**Issue by pretorh** [pretorh/lfs-notes#6]
Remove scripts no longer needed after LFS 10, LFS 11. Remove step files that are deprecated. Rearrange and renumber the step and script files

**Comment by pretorh** [comment]
todo:

- [x] rename files to be in correct order (#11)
- [x] rename scripts (#11 and #12)
- [x] general step cleanup (fix headings, add index for steps) (#17)
- [x] script cleanup (recheck usage, rearrange and rename) (#18)
- [ ] combine system config and finalize as the last step (move bootable before it)
